language: node_js
node_js:
- 8
before_install:
- npm i -g firebase-tools
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: firebase
  project: fir-travis-c121d
  skip_cleanup: true
  token:
    secure: k9uXwh4R3zRa+6XUslws0Kgj7TAMEWE88YLkGoupaXizzmajp93/RPAa86iwS3CkrTfhDSDwJymMn/ZLMxE2EOoFfyGkz5AZ/Ne7M9JNmu4SUX0F0+CCApyJd2CXFGm1HE9LXI2rQPJmHSQW7mo9i5Zu/1kyPbqUgn7IZL+owld2/3ik2n0mgy17rn76fHEYZGTD9iGsFoTlb+o/zLKZThJONMfvQPRCOAm/9FKB2YKWhULMZoS5KTuTcLbAoAf9fDXrg9L4f3Iwp5ZymZyqd4wfrn2ALwM+7+RjPcmUM0S91fJq8uzvwdRG6iSugheFaymUMEWjTD4SOSAii+dHNUqnsyiAxWa7fgbXLwuTOeE7fR4jgHaYiQp1pz7ij9zRMVV4MVDZNQ+mPyB7XR9IHU9UGj0RoytB2yezbQUgnEkpDW1EChaxAYsRISaky1D41lK9DM/Or5PCHgBn0XPfEgp15D88Wg0Adewczvpu0QiS8t+/gz5MTyEAf3hhA2U4F2P7qUajNfYqvGjPC7tHgyCr5I+uWT7B8NuyyvZ6NLA0nCxOlScXTSwan2GKZZ1PnozIzJMDnwBuHyXfHxJPtJFEcgFM7mXK/VScHALeHpI+ij4mKy4JzdRBurJJBlXTxwsrHBxZDPPUrKr8pMGn/Jd7fekBUG64zFNiCZtZQ/E=
